services:
  app:
    container_name: flo_app
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: 'flo-net-postgres'
      GIN_MODE: ${GIN_MODE}
      POSTGRES_PORT: 5432
    links:
      - flo-net-postgres
    volumes:
      - api:/usr/src/app/
    depends_on:
      - flo-net-postgres
    networks:
      - flo-net

  flo-net-postgres:
    image: postgres:latest
    container_name: flo_db_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # - DATABASE_HOST=${DB_HOST} 
    ports:
      - "5432:5432"
    volumes:
      - flo_database_postgres:/var/lib/postgresql/data
      # - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
    networks:
      - flo-net
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   depends_on:
  #     - flo-net-postgres
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - flo-net
  #   restart: unless-stopped

volumes:
  api:
  flo_database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  flo-net:
    driver: bridge